name: Bug Report
description: File a bug report
title: "[Issue: Bug Report]: "

body:

- type: checkboxes
  id: verification
  attributes:
    description: |
      Thanks for taking the time to fill out this bug report!
      Bug Report issues are for concrete, actionable bugs only
    options:
      - label: Green
        required: true
  validations:
    required: false

- type: input
  id: contact
  attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more info?
    placeholder: ex. email@example.com
  validations:
    required: false

- type: textarea
  id: what-happened
  attributes:
    label: Bug Summary
    description: "Briefly describe the problem."
  validations:
    required: true   

- type: checkboxes
  id: checkboxes
  attributes:
    label: Select the relevant components
    description: You may select more than one.
    options:
      - label: UI
      - label: API
      - label: Docs
      - label: Other
  validations:
    required: false

# DROPDOWN:
- type: dropdown
  id: deployment
  attributes:
    label: deployment method
    description: How did you install application?
    options:
      - kubernetes
      - docker
      - other
  validations:
    required: true

# DROPDOWN:
- type: dropdown
  id: modifications
  attributes:
    label: Modifications
    description: Have you modified the installation, deployment topology, or container images in any way? If yes, please explain in the "additional information" field at the bottom of the form
    options:
      - "NO"
      - "Yes"
  validations:
    required: true

- type: textarea
  id: version
  attributes:
    label: application version
    description: "What version of the application are you running?"
  validations:
    required: true 

- type: textarea
  id: version
  attributes:
    label: Operating system
    description: "What operating system are you using?"
  validations:
    required: true

# DROPDOWN:
- type: dropdown
  id: download
  attributes:
    label: web browser
    description: Which browsers are affected?
    options:
      - Firefox
      - Chrome
      - Edge
  validations:
    required: false

- type: textarea
  id: description
  attributes:
    label: Steps to reproduce
    description: "Starting from a new installation of the system, describe exactly how a developer or quality engineer can reproduce the bug on infrastructure that isn't yours. Include any and all resources created, input values, test users, roles assigned, playbooks used, etc."
  validations:
    required: true

- type: textarea
  id: Actual
  attributes:
    label: Expected results
    description: "What did you expect to happpen when running the steps above?"
  validations:
    required: true

- type: textarea
  id: actual
  attributes:
    label: Actual results
    description: "What actually happened?"
  validations:
    required: true
  
- type: textarea
  id: Additional
  attributes:
    label: Additional information
    description: "Include any relevant log output, links to sosreport, database dumps, screenshots, or other information."
  validations:
    required: false


