name: deploy
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: get-code
        uses: actions/checkout@v4
      - name: install_nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install_dependencies
        run: npm ci
      - name: run_lint
        run: npm run lint
      - name: run_tests
        run: npm run test
      - name: run_build
        run: npm run build
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: get-code
        uses: actions/checkout@v4
      - name: install_nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install_dependencies
        run: npm ci
      - name: run_tests
        run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: get-code
        uses: actions/checkout@v4
      - name: install_nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install_dependencies
        run: npm ci
      - name: run_build
        run: npm run build
